### ISSUE TITLE
Error when I include

### ISSUE THREAD

**Issue by YaroslavG** [kunalnagar/facebook-send#2]
Hello,
I have a error when I include your component to my project: 
Uncaught TypeError: Cannot read property 'parentNode' of undefined  facebook-send.html:103

**Comment by kunalnagar** [comment]
Have you seen the demo page? There is no such error: http://kunalnagar.github.io/facebook-send/components/facebook-send/demo.html

Maybe its an issue from your side?

**Comment by YaroslavG** [comment]
yes, I see! Demo page is work fine!
But when I added this component to my project I get error. 
I did it from your instruction http://component.kitchen/components/kunalnagar/facebook-send 
Standard developer installation it is a simple 
maybe need to add anything else?

**Comment by kunalnagar** [comment]
I don't see any error in my console. Here is a screenshot:

![screen shot 2015-05-06 at 7 41 46 pm](https://cloud.githubusercontent.com/assets/2741371/7494916/4a5bed46-f428-11e4-8345-3db58d31d1ba.png)

**Comment by YaroslavG** [comment]
It does not work for me locally
If I send you my code you can check it and help?

**Comment by YaroslavG** [comment]
Sorry Kunal,
 I had said something wrong? 
Why you closed issue?

**Comment by kunalnagar** [comment]
I'm sorry but I can't help you with your local code. I'm unable to understand how you're getting an error on your local environment when the URL you sent me does not show any error. This is why I closed the issue. You can probably debug it and solve it yourself.

**Comment by YaroslavG** [comment]
Thank you for answer Kunal,
But I still do not understand why I get an error if I follow strictly according to instructions...

**Comment by YaroslavG** [comment]
Very fun, Sorry to trouble you, Kunal :)
I forgot to include in my project jQuery, I think this should not forget to mention in your "Readme.md".

**Comment by YaroslavG** [comment]
just question: 
It is can work from mobile device? example Ionic/Cordova platform?

**Comment by kunalnagar** [comment]
I'm not sure about Ionic/Cordova. I haven't tested it there. You can test it and let me know as well?

**Comment by YaroslavG** [comment]
I check this on my Cordova app, and it is not working. Works only when I run it from server.
